
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysiwkrehjmccxpihqntv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzaXdrcmVoam1jY3hwaWhxbnR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNjgxNjgsImV4cCI6MjA1Nzk0NDE2OH0.fehto6WE2OMWuMy6laWM-tkak6YME9Ax61Y1VToQtEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
